# 28181 SIP服务器的配置
sip-server:
  # [必须修改] SIP服务器IP
  ip: SIP服务器IP
  # 28181服务监听的端口
  port: 5060
  # 根据国标6.1.2中规定，domain宜采用ID统一编码的前十位编码。国标附录D中定义前8位为中心编码（由省级、市级、区级、基层编号组成，参照GB/T 2260-2007）
  # 后两位为行业编码，定义参照附录D.3
  # 3701020049标识山东济南历下区 信息行业接入
  domain: ${WVP_DOMAIN:4401020049}
  id: ${WVP_ID:44010200492000000001}
  # [可选] 默认设备认证密码，后续扩展使用设备单独密码, 移除密码将不进行校验
  password: ${WVP_PWD:admin123}
  #心跳周期
  keepaliveTimeOut: 30

#作为28181设备的配置
sip-device:
  # [必须修改] 本机的IP
  ip: 本机的IP
  # 28181服务监听的端口
  port: 5080
  #
  id: 64010000001110000001
  #默认设备认证密码
  password: admin123

ffmpeg:
  #ffmpeg执行文件路径
  path: D:\Program Files\ffmpeg\bin\ffmpeg.exe
  #模拟推送视频流的命令
  pushStreamCmd: -re -i {filePath} -vcodec h264 -acodec aac -f rtp_mpegts rtp://{ip}:{port}
spring:
  redis:
    database: 1
    port: 6379
    host: 127.0.0.1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
#      url: jdbc:sqlite::resource:gb28181-client.sqlite
#      driver-class-name:  org.sqlite.JDBC
#      username:
#      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:4306/gb28181-client?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true
      username: root
      password: root
logging:
  level:
    com.wydpp: debug
#    com.wydpp.mapper: info


